version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    networks:
      default:
        ipv4_address: 172.23.0.51
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Moscow
      - UMASK_SET=022 #optional
    volumes:
      - ./sonarr/config:/config
      - ./TV:/tv
      - ./downloadclient-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    networks:
      default:
        ipv4_address: 172.23.0.52
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Moscow
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr/config:/config
      - ./Films:/movies
      - ./downloadclient-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    networks:
      default:
        ipv4_address: 172.23.0.53
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Moscow
      - UMASK_SET=022
      - WEBUI_PORT=8068
    volumes:
      - ./qbittorrent/config:/config
      - ./downloadclient-downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8068:8068
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    networks:
      default:
        ipv4_address: 172.23.0.54
    container_name: jackett
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Moscow
      # - RUN_OPTS=run options here #optional
    volumes:
      - ./jackett/config:/config
      - ./downloadclient-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  gramarrru:
    image: memodota/gramarrru
    networks:
      default:
        ipv4_address: 172.23.0.55
    container_name: gramarrru
    depends_on:
      - sonarr
      - radarr
    volumes:
      - ./gramarr/config.json:/config/config.json      
    restart: unless-stopped

networks:
    default:
        external:
            name: nginx-proxy
